### ISSUE TITLE
Planned Features Tracker

### ISSUE THREAD

**Issue by newwby** [newwby/Godoct#3]
# Task List

### Output Changes
- [ ] Create API index page on doc generation, with links to subpages

### Executable Changes
- [ ] Add landing page on running (with `/help --h` functions, and ignore `include` flag to generate all in target directory recursively).
- [ ] Add startup arguments that can execute with landing page args.

### Logic Changes
- [ ] Handle inner/sub classes in a script (e.g., `LogRecord` in global log)
- [ ] Walk through .gd files rather than passing line contents (interpret file once rather than with submethods)
- [ ] Add more type hinting in function arguments and statically type function return values.
- [ ] Create different mains for generating markdown versus generating reStructuredText (RST).
  - [ ] Move the validating logic to a separate Python file.
  - [ ] Move the parsing/sorting logic to a separate Python file.
- [ ] Add f-string constants in the generation file so the same data fetching script can apply to different f-strings for MD vs RST.
- [ ] Add support for handling identically named files (output by path where there's a conflict)

### Testing
- [ ] Set up `pytest` and add tests for:
  - [ ] Various ways to write arguments, functions, and variables.
  - [ ] Comments in unusual places.
  - [ ] Multiline function/variable declarations.
  - [ ] Multiline arguments.
  - [ ] Different combinations of static typing, default arguments, neither/either.

### Organisation/Documenetation
- [ ] Set up issue templates
  - [ ] bug report
  - [ ] feature suggestion
- [X] Convert all `TODO` notes to repository issues.
- [X] Write documentation/walkthrough on how to write docs for GDscript files to pick up.
  - [X] Specify about using `##` documentation lines.
  - [X] Specify how documentation lines must precede properties/functions.
  - [X] Specify about class docstring and how to use empty lines.
  - [X] Give examples.
  - [X] Specify how the include file works.
- [ ] Add documentation for Godoct methods
  - [ ] Add docstrings for Sphinx/RTD to pick up.
  - [ ] Write README/landing page about Godoct for GitHub.
  - [ ] Write another for RTD index.
